### ISSUE TITLE
[Bug] Bad character escape sequence (4:123)

### ISSUE THREAD

**Issue by FisNew** [ecomfe/san-cli#41] opened 2020-07-08 13:21 UTC
版本
0.1.0

运行环境：
node: 10.13.0
windows10

描述：

按照官方文档运行
san int ksky521/san-project

然后
npm install
npm start

报错
 ERROR  F:\ksky521\san-project\src\pages\index\containers\app.js: unknown: Bad character escape sequence (4:123)
`
    2 |     if (module.hot) {
    3 |         var __HOT_API__ = 
                    require('node_modules\_san-hot-loader@0.1.1@san-hot-loader\lib\runtime\component-client-api.js');
  > 4 |         var __HOT_UTILS__ = require('node_modules\_san-hot-loader@0.1.1@san-hot-loader\lib\runtime\utils.js');
      |                                                                                                                            ^
    5 |
    6 |         var __SAN_COMPONENT__ = __HOT_UTILS__.getExports(module);
    7 |         if (__SAN_COMPONENT__.template || __SAN_COMPONENT__.prototype.template) {
  at Parser._raise (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:757:17)
  at Parser.raiseWithData (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:750:17)
  at Parser.raise (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:744:17)
  at Parser.readHexChar (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:8622:14)
  at Parser.readCodePoint (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:8423:19)
  at Parser.readEscapedChar (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:8549:29)
  at Parser.readString (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:8443:21)
  at Parser.getTokenFromCode (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:8098:14)
  at Parser.nextToken (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:7625:12)
  at Parser.next (node_modules\_@babel_parser@7.10.4@@babel\parser\lib\index.js:7550:10)
  @ ./src/pages/index/index.js 7:34-61
  @ multi ./node_modules/_webpack-dev-server@3.11.0@webpack-dev-server/client?http://192.168.0.106:8888/sockjs-node (webpack)/hot/only-dev-server.js ./src/pages/index/index.js
`

**Comment by Lohoyo** [comment] 2020-07-08 13:28
感谢你的反馈，我们今天就开始处理这个问题。

**Comment by ksky521** [comment] 2020-07-10 04:42
Duplicate of #42 已解决

**Closed by ksky521** 2020-07-10 04:42 UTC
